### ISSUE TITLE
404 (http://nicohinderling.com/projects.html)

### ISSUE THREAD

**Issue by benlawson** [NicoHinderling/NicoHinderling.github.io#1]
broken link when I click 'overview' under projects

**Comment by NicoHinderling** [comment]
Hi sir. I've resolved the issue. I forgot that I removed my projects.html page a while ago. 

Best,
:^)

**Comment by benlawson** [comment]
all in days work. also another broken link in readme.md (looks like you upgraded from .me to .com)

xoxo

**Comment by NicoHinderling** [comment]
what would i do without you.

resolved btw :sob:
